/**
 * An enumeration of possible messages.
 */
public enum Message {

    ADD_TASK,
    COMMAND_NOT_RECOGNIZED,
    DATE_NOT_RECOGNIZED,
    DELETE,
    DONE,
    EMPTY_COMMAND,
    GOODBYE,
    INDEX_NAN,
    INVALID_ARGUMENT,
    IO_ERROR,
    ITEM_NOT_FOUND,
    LIST,
    MISSING_DATE,
    MISSING_DATE_TIME,
    MISSING_DEADLINE,
    MISSING_DELETE_INDEX,
    MISSING_DESCRIPTION,
    MISSING_DONE_INDEX,
    MISSING_END_TIME,
    MISSING_FIND_INDEX,
    NO_TASK,
    NO_TASK_ON_DATE,
    TASK_COMPLETED,
    TASK_COUNT,
    TASK_FOUND,
    TASK_NOT_FOUND
}
