package duke;

/**
 * Main class for the entire program, Duke is the chatbot and this is the driver class.
 */
public class Duke {

    /**
     * TaskList to store all the Tasks for Duke.
     */
    private TaskList taskList;

    /**
     * Storage file for reading when initialising or writing to when there are changes to the TaskList.
     */
    private Storage file;

    /**
     * Handles the User Interactions/Formalities.
     */
    private Ui ui;

    /**
     * Constructor for Duke.
     */
    public Duke() {

        // Assignment of objects
        this.taskList = new TaskList();
        this.ui = new Ui();
        this.file = new Storage();

        // Load any last saved user data, else create a new file to store future data
        this.initialisePastUserData();

    }

    /**
     * Runs TaskList to serve the user.
     *
     * @param command the user input for Duke to process.
     * @return String response generated by Duke to present in the GUI.
     */
    public String run(String command) {
        return taskList.serveUser(command);
    }

    /**
     * Loads previously saved files if any. Creates new file otherwise.
     */
    public void initialisePastUserData() {
        // Updates taskList to last saved items
        file.readFromLastSavedFile(taskList);
    }

}
