package duke;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;

/**
 * Controller for duke.MainWindow. Provides the layout for the other controls.
 */
public class MainWindow extends AnchorPane {
    @FXML
    private ScrollPane scrollPane;
    @FXML
    private VBox dialogContainer;
    @FXML
    private TextField userInput;
    @FXML
    private Button sendButton;

    private Duke duke;

    /* I do not own the rights to these photos. These photos have been taken from the following websites:
    https://en.wikipedia.org/wiki/Night_King
    https://m.buro247.sg/images/culture/game-of-thrones-jamie-lannister-burosingapore-ca.jpg
     */
    private Image userImage = new Image(this.getClass().getResourceAsStream("/images/DaUser.jpeg"));
    private Image dukeImage = new Image(this.getClass().getResourceAsStream("/images/DaDuke.jpg"));

    /**
     * The first method that runs when the Application starts, to greet User.
     */
    @FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());

        dialogContainer.getChildren().addAll(
                DialogBox.getDukeDialog(Ui.showWelcomeMessage(), dukeImage)
        );
    }

    /**
     * Sets the Duke object from higher-level nodes to MainWindow node.
     * @param d Duke object that contains the main logic behaviour of the application.
     */
    public void setDuke(Duke d) {
        duke = d;
    }

    /**
     * Creates two dialog boxes, one echoing user input and the other containing Duke's reply and then appends them to
     * the dialog container. Clears the user input after processing.
     */
    @FXML
    private void handleUserInput() {
        String input = getUserResponse(userInput.getText());
        String response = getDukeResponse(userInput.getText());

        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(input, userImage), DialogBox.getDukeDialog(response, dukeImage));
        userInput.clear();
        // if Duke responds with goodbye message, terminate program.
        if (response.equals("Duke: " + "\n" + "\n" + "It was my pleasure assisting you. Keep smiling while you can."
                + " Winter is coming." + "\n")) {
            System.exit(0);
        }
    }

    /**
     * Returns an echoed user input.
     * @param input Instruction inputted by user.
     * @return A
     */
    private String getUserResponse(String input) {
        return "You: " + "\n" + input;
    }

    /**
     * Returns the response to user input.
     * @param input User input.
     * @return Response to user input, generated by Duke object.
     */
    private String getDukeResponse(String input) {
        String result = duke.run(input);
        return "Duke: " + "\n" + result;
    }
}
