package duke;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * A JUnit test to test correctness of ToDo Object.
 */
public class ToDoTest {
    @Test
    /**
     * A test to make sure that the string generated by writeDrive() method in ToDo object is correct.
     */
    public void runTest(){
        assertEquals(new ToDo("read").writeDrive(), "T|0|read");
    }
}
