package dukebot;

public enum LineName {
    NO_INPUT,
    DUKE,
    LIST,
    LIST_EMPTY,
    LIST_EXISTS,
    DONE_EMPTY,
    DONE_OUT_OF_INDEX,
    DONE_ALREADY,
    DONE_SUCCESS,
    NOT_A_NUMBER,
    DELETE_EMPTY,
    DELETE_OUT_OF_INDEX,
    DELETE_SUCCESS,
    TODO_EMPTY,
    DEADLINE_EMPTY,
    DATE_TIME_PARSE_FAIL,
    DEADLINE_BY_MISSING,
    EVENT_EMPTY,
    EVENT_AT_MISSING,
    EXIT,
    INVALID_COMMAND,
    ERROR_PLACEHOLDER;
}