package dukebot.ui;

public enum LineName {
    DATE_TIME_PARSE_FAIL,
    DEADLINE_BY_MISSING,
    DEADLINE_EMPTY,
    DELETE_EMPTY,
    DELETE_OUT_OF_INDEX,
    DONE_ALREADY,
    DONE_EMPTY,
    DONE_OUT_OF_INDEX,
    DONE_SUCCESS,
    ERROR_PLACEHOLDER,
    EVENT_AT_MISSING,
    EVENT_EMPTY,
    EXIT,
    HELP,
    INVALID_COMMAND,
    LIST,
    LIST_EMPTY,
    LIST_EXISTS,
    LOAD_FAIL,
    NOT_A_NUMBER,
    NO_INPUT,
    SAVE_FAIL,
    SAY_DUKE,
    TODO_EMPTY;
}